<robot name="edumip" xmlns:xacro="http://www.ros.org/wiki/xacro">

    <xacro:property name="wheel_separation" value="0.070" />
    <xacro:property name="wheel_radius" value="0.034" />
    <xacro:property name="wheel_width" value="0.010" />
    <xacro:property name="body_height" value="0.1" />
    <xacro:property name="body_width" value="0.050" />
    <xacro:property name="body_length" value="0.035" />
    <xacro:property name="left_origin">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:property>

    <xacro:property name="right_origin">
        <origin xyz="0 0 0" rpy="0 0 0"/>
    </xacro:property>

    <xacro:macro name="wheel" params="prefix width radius *origin">
        <link name="${prefix}_wheel">
            <inertial>
                <origin xyz="0 0 0" rpy="0 0 0"/>
                <mass value="0.030"/>
                <inertia ixx="1.75e-5" ixy="0" ixz="0" iyy="1.75e-5" iyz="0" izz="1.75e-5"/>
            </inertial>
            <visual>
                <origin xyz="0 0 0" rpy="1.57 0 0"/>
                <geometry>
                    <cylinder length="${width}" radius="${radius}"/>
                </geometry>
            </visual>
            <collision>
                <origin xyz="0 0 0" rpy="1.57 0 0"/>
                <geometry>
                    <cylinder length="${width}" radius="${radius}"/>
                </geometry>
            </collision>
        </link>
    </xacro:macro>

    <xacro:macro name="edumip">

        <link name="base_link">
            <visual>
                <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
                <geometry>
                    <box size="${body_length} ${body_width} ${body_height}"/>
                </geometry>
                <material name="Blue">
                    <color rgba="0 0.0 1.0 0.5"/>
                </material>
            </visual>
            <collision>
                <origin xyz="0 0 ${0.5*body_height}" rpy="0 -0.20 0"/>
                <geometry>
                    <box size="${body_length} ${body_width} ${body_height}"/>
                </geometry>
            </collision>
            <inertial>
                <origin xyz="0 0 ${0.5*body_height}" rpy="0 0 0"/>
                <mass value="0.180"/>
                <inertia ixx="6.0e-4" ixy="0" ixz="0" iyy="6.0e-4" iyz="0" izz="6.0e-4"/>
            </inertial>
        </link>

        <xacro:wheel prefix="left" 
                    width="${wheel_width}"
                    radius="${wheel_radius}">
            <xacro:insert_block name="left_origin" />
        </xacro:wheel>

        <xacro:wheel prefix="right" 
                    width="${wheel_width}"
                    radius="${wheel_radius}">
            <xacro:insert_block name="right_origin" />
        </xacro:wheel>

        <joint name="left_joint" type="continuous">
            <origin xyz="0 ${-0.5*wheel_separation} 0" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="left_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>

        <joint name="right_joint" type="continuous">
            <origin xyz="0 ${0.5*wheel_separation} 0" rpy="0 0 0"/>
            <parent link="base_link"/>
            <child link="right_wheel"/>
            <axis xyz="0 1 0"/>
        </joint>
        
    </xacro:macro>
</robot>
